services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    develop:
      watch:
        - action: sync
          path: ./Backend
          target: /Backend
        - action: rebuild
          path: ./Backend/package.json
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://127.0.0.1:5000"
